
import { UserRole, DefaultSubscriptionPlanId, SubscriptionPlan, Translations, WorkoutVideo, Recipe, SubscriptionPlanFeature } from './types';

export const APP_NAME = "My Fit Coach";
export const ADMIN_EMAIL = "lolelarap@gmail.com"; // Hardcoded admin email updated

export const THEME_COLORS = {
  primary: 'sky-600', 
  primaryHover: 'sky-700',
  secondary: 'lime-500',
  secondaryHover: 'lime-600',
  accent: 'rose-500', // Changed from amber
  accentHover: 'rose-600',
  background: 'slate-900', // Slightly softer dark
  surface: 'slate-800', // For cards, modals
  textPrimary: 'slate-100', // Brighter white for primary text
  textSecondary: 'slate-400', // Softer gray for secondary text
  error: 'red-500',
  success: 'green-500',
};

export const COUNTRIES_LIST = [
  { code: '', name: 'اختر الدولة...' }, // Default empty option
  { code: 'EG', name: 'مصر' },
  { code: 'SA', name: 'السعودية' },
  { code: 'AE', name: 'الإمارات العربية المتحدة' },
  { code: 'KW', name: 'الكويت' },
  { code: 'QA', name: 'قطر' },
  { code: 'BH', name: 'البحرين' },
  { code: 'OM', name: 'عمان' },
  { code: 'JO', name: 'الأردن' },
  { code: 'LB', name: 'لبنان' },
  { code: 'DZ', name: 'الجزائر' },
  { code: 'MA', name: 'المغرب' },
  { code: 'TN', name: 'تونس' },
  { code: 'US', name: 'الولايات المتحدة' },
  { code: 'GB', name: 'المملكة المتحدة' },
  { code: 'CA', name: 'كندا' },
  { code: 'AU', name: 'أستراليا' }, // Corrected entry
  { code: 'DE', name: 'ألمانيا' },
  { code: 'FR', name: 'فرنسا' },
  // Add more countries as needed
];

export const TRANSFORMATION_IMAGE_MAX_SIZE_BYTES = 2 * 1024 * 1024; // 2MB

export const AR_TRANSLATIONS: Translations = {
  appName: "My Fit Coach",
  tagline: "مدربك الشخصي نحو صحة أفضل",
  login: "تسجيل الدخول",
  register: "إنشاء حساب جديد",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  name: "الاسم الكامل",
  phoneNumber: "رقم الهاتف",
  country: "الدولة",
  confirmPassword: "تأكيد كلمة المرور",
  dashboard: "لوحة التحكم",
  profile: "الملف الشخصي",
  workouts: "تمارين الفيديو",
  nutrition: "التغذية",
  subscriptions: "الاشتراكات",
  adminPanel: "لوحة الإدارة",
  logout: "تسجيل الخروج",
  myStats: "إحصائياتي",
  currentPlan: "خطتي الحالية",
  noActivePlan: "ليس لديك خطة اشتراك نشطة.",
  browsePlans: "تصفح خطط الاشتراك",
  workoutVideos: "مكتبة تمارين الفيديو",
  recipes: "وصفات صحية",
  calorieCalculator: "حاسبة السعرات الحرارية اليومية", // Updated for clarity
  nutritionAIAssistant: "مساعد التغذية الذكي",
  askNutritionQuestion: "اطرح سؤالاً عن التغذية...",
  submit: "إرسال",
  saveChanges: "حفظ التغييرات",
  manageUsers: "إدارة المستخدمين",
  manageVideos: "إدارة الفيديوهات",
  manageRecipes: "إدارة الوصفات",
  approveSubscriptions: "الموافقة على الاشتراكات",
  manageSubscriptionPlans: "إدارة خطط الاشتراك",
  addSubscriptionPlan: "إضافة خطة اشتراك جديدة",
  editSubscriptionPlan: "تعديل خطة الاشتراك",
  planName: "اسم الخطة",
  planPrice: "السعر",
  planCurrency: "العملة",
  planDescription: "وصف الخطة",
  planFeatures: "ميزات الخطة",
  addFeature: "إضافة ميزة",
  confirmDeletePlan: "هل أنت متأكد أنك تريد حذف خطة الاشتراك هذه؟ قد يكون هناك مستخدمون مشتركون بها.",
  pendingSubscriptions: "طلبات اشتراك معلقة",
  noPendingSubscriptions: "لا توجد طلبات اشتراك معلقة.",
  approve: "موافقة",
  reject: "رفض",
  setDuration: "تحديد المدة (أيام)",
  user: "المستخدم",
  plan: "الخطة",
  status: "الحالة",
  action: "الإجراء",
  actions: "إجراءات",
  addVideo: "إضافة فيديو جديد",
  videoTitle: "عنوان الفيديو",
  videoDescription: "وصف الفيديو",
  videoURL: "رابط الفيديو (Embed URL)",
  videoThumbnailURL: "رابط الصورة المصغرة (اختياري)",
  videoDuration: "مدة الفيديو (دقائق)",
  videoCategory: "فئة الفيديو",
  addRecipe: "إضافة وصفة جديدة",
  recipeName: "اسم الوصفة",
  recipeDescription: "وصف الوصفة",
  ingredients: "المكونات",
  addIngredient: "إضافة مكون",
  instructions: "التعليمات",
  addInstructionStep: "إضافة خطوة",
  prepTime: "وقت التحضير (دقائق)",
  cookTime: "وقت الطهي (دقائق)",
  servings: "عدد الحصص",
  recipeImageURL: "رابط صورة الوصفة (اختياري)",
  recipeCategory: "فئة الوصفة",
  caloriesPerServing: "السعرات الحرارية لكل حصة (اختياري)",
  upload: "رفع",
  foodItem: "العنصر الغذائي",
  calories: "السعرات الحرارية", // Generic label for calories input
  addItem: "إضافة عنصر",
  totalCalories: "إجمالي السعرات الحرارية",
  weightKg: "الوزن (كجم)",
  heightCm: "الطول (سم)",
  bodyFatPercentage: "نسبة الدهون (%)",
  progressNotes: "ملاحظات التقدم",
  addNote: "إضافة ملاحظة",
  subscribe: "اشترك الآن",
  subscribed: "مشترك",
  pendingApproval: "في انتظار الموافقة",
  active: "نشط",
  expired: "منتهي الصلاحية",
  rejected: "مرفوض",
  cancelled: "ملغى",
  subscriptionDetails: "تفاصيل الاشتراك",
  expiresOn: "ينتهي في",
  manageContent: "إدارة المحتوى",
  welcomeAdmin: "مرحباً أيها المدير",
  adminTagline: "إدارة شاملة لتطبيقك الرياضي.",
  errorOccurred: "حدث خطأ. الرجاء المحاولة مرة أخرى.",
  passwordsDoNotMatch: "كلمتا المرور غير متطابقتين.",
  registrationSuccessful: "تم التسجيل بنجاح! يمكنك الآن تسجيل الدخول.",
  loginFailed: "فشل تسجيل الدخول. تحقق من بياناتك.",
  accessDenied: "الدخول محظور. يجب أن تكون مشتركًا للوصول لهذه الصفحة.",
  adminAccessOnly: "هذه الصفحة مخصصة للمسؤولين فقط.",
  loading: "جاري التحميل...",
  enterYourMessage: "اكتب رسالتك هنا...",
  sendMessage: "إرسال الرسالة",
  aiThinking: "المساعد يفكر...",
  copiedToClipboard: "تم النسخ إلى الحافظة!",
  delete: "حذف",
  edit: "تعديل",
  cancel: "إلغاء",
  confirm: "تأكيد",
  confirmDelete: "هل أنت متأكد أنك تريد الحذف؟ هذا الإجراء لا يمكن التراجع عنه.",
  all: "الكل",
  breakfast: "فطور",
  lunch: "غداء",
  dinner: "عشاء",
  snack: "وجبة خفيفة",
  cardio: "كارديو",
  strength: "قوة",
  flexibility: "مرونة",
  featureText: "نص الميزة",
  pricePlaceholder: "مثال: 29.99",
  currencyPlaceholder: "مثال: USD أو SAR",
  defaultDurationDays: "المدة الافتراضية (أيام)", 
  pageNotFound: 'الصفحة غير موجودة',
  pageNotFoundText: 'عذرًا، الصفحة التي تبحث عنها غير موجودة.',
  goHome: 'العودة إلى الصفحة الرئيسية',
  loadingWorkoutVideos: 'جاري تحميل التمارين...',
  searchVideos: 'ابحث عن التمارين...',
  allCategories: 'جميع الفئات',
  noVideosFound: 'لم يتم العثور على فيديوهات تطابق بحثك.',
  duration: 'المدة',
  minutes: 'دقائق',
  loadingVideo: 'جاري تحميل الفيديو...',
  videoNotFound: 'الفيديو غير موجود.',
  category: 'الفئة',
  videoDisplayDescriptionLabel: 'الوصف', // Changed from 'description' to be more specific
  searchRecipes: 'ابحث عن الوصفات...',
  noRecipesFound: 'لم يتم العثور على وصفات تطابق بحثك.',
  perServing: 'لكل حصة',
  calUnit: 'سعر حراري',
  item: 'العنصر',
  quantity: 'الكمية',
  step: 'الخطوة',
  optional: 'اختياري',
  yoga: 'يوغا',
  hiit: 'تمارين عالية الكثافة (HIIT)',
  dessert: 'حلوى',
  drinks: 'مشروبات',
  aiError: 'عذرًا، حدث خطأ أثناء التواصل مع المساعد.',
  noAccountPrompt: 'ليس لديك حساب؟ سجل الآن',
  hasAccountPrompt: 'لديك حساب بالفعل؟ سجل الدخول',
  emailInUseError: 'هذا البريد الإلكتروني مستخدم بالفعل.',
  addNotePlaceholder: 'اكتب ملاحظة جديدة عن تقدمك...',
  noNotesYet: 'لا توجد ملاحظات تقدم بعد.',
  editStats: 'تعديل الإحصائيات',
  profileUpdatedSuccess: 'تم تحديث الملف الشخصي بنجاح!',
  subscriptionRequestedSuccess: 'تم إرسال طلب اشتراكك بنجاح. ستتم مراجعته قريبًا.',
  noPlansAvailable: 'لا توجد خطط اشتراك متاحة حاليًا.',
  adminNavigation: 'التنقل الإداري',
  role: 'الدور',
  siteManager: "مدير الموقع",
  subscriptionStatus: 'حالة الاشتراك',
  notSubscribedYet: 'لم يشترك بعد',
  planNotFoundOrDeleted: 'الخطة محذوفة أو غير موجودة',
  confirmDeleteVideo: 'هل أنت متأكد أنك تريد حذف هذا الفيديو؟',
  editVideo: 'تعديل الفيديو',
  confirmDeleteRecipe: 'هل أنت متأكد أنك تريد حذف هذه الوصفة؟',
  editRecipe: 'تعديل الوصفة',
  noPlansDefined: 'لا توجد خطط اشتراك معرفة حاليًا.',
  rejectedByAdmin: 'تم الرفض بواسطة الإدارة',
  requested: 'مطلوب',
  daysDurationHelp: 'أدخل عدد أيام صلاحية الاشتراك بالرقم.',
  durationDaysPlaceholder: 'مثال: 30',

  // Admin Promotion
  promoteToAdmin: "ترقية إلى مسؤول",
  demoteToUser: "تخفيض إلى مستخدم",
  confirmPromotion: "هل أنت متأكد أنك تريد ترقية هذا المستخدم إلى مسؤول؟",
  confirmDemotion: "هل أنت متأكد أنك تريد تخفيض هذا المسؤول إلى مستخدم؟",
  cannotDemoteSelf: "لا يمكنك تخفيض دورك كمدير للموقع.",
  roleUpdatedSuccess: "تم تحديث دور المستخدم بنجاح.",
  cannotModifySiteManager: "لا يمكن تعديل دور مدير الموقع الأساسي.",
  actionNotAllowed: "الإجراء غير مسموح به.",

  // PDF Library
  managePdfs: "إدارة ملفات PDF",
  pdfLibrary: "مكتبة PDF",
  uploadPdf: "رفع ملف PDF",
  myDocuments: "مستنداتي",
  downloadPdf: "تحميل PDF",
  assignToUsers: "تعيين لمستخدمين",
  pdfFileName: "اسم الملف",
  pdfDescription: "وصف الملف",
  selectPdfFile: "اختر ملف PDF",
  noPdfsAssigned: "لا توجد ملفات PDF مخصصة لك حاليًا.",
  noPdfsUploaded: "لم يتم رفع أي ملفات PDF بعد.",
  confirmDeletePdf: "هل أنت متأكد أنك تريد حذف ملف PDF هذا؟",
  editPdfAssignments: "تعديل تعيينات PDF",
  pdfUploadedSuccess: "تم رفع ملف PDF بنجاح.",
  pdfDeletedSuccess: "تم حذف ملف PDF بنجاح.",
  pdfUpdatedSuccess: "تم تحديث ملف PDF بنجاح.",
  selectUsersToAssign: "اختر المستخدمين لتعيين الملف لهم:",
  assignedUsers: "المستخدمون المعين لهم:",

  // Site Manager User Editing
  editUserInfo: "تعديل معلومات المستخدم",
  deleteUser: "حذف المستخدم",
  confirmDeleteUser: "هل أنت متأكد أنك تريد حذف المستخدم {userName}؟ سيتم حذف جميع بياناته المتعلقة بالاشتراكات وملفات PDF.",
  confirmEmailChange: "هل أنت متأكد أنك تريد تغيير البريد الإلكتروني للمستخدم؟ قد يحتاج المستخدم لتسجيل الدخول بالبريد الجديد.",
  newPassword: "كلمة المرور الجديدة",
  confirmNewPassword: "تأكيد كلمة المرور الجديدة",
  userDeletedSuccess: "تم حذف المستخدم بنجاح.",
  userInfoUpdatedSuccess: "تم تحديث معلومات المستخدم بنجاح.",
  cannotDeleteSelfAccount: "لا يمكنك حذف حسابك كمدير للموقع.",
  cannotEditSelfDetailsInThisModal: "لتعديل تفاصيل حسابك، يرجى استخدام صفحة الملف الشخصي.",
  emailAlreadyExists: "هذا البريد الإلكتروني مستخدم بالفعل من قبل مستخدم آخر.",
  fieldRequired: "هذا الحقل مطلوب.",
  pleaseSelectCountry: "يرجى اختيار الدولة.",

  // Global Notifications
  globalNotifications: "الإشعارات العامة",
  sendGlobalNotification: "إرسال إشعار عام",
  notificationMessage: "نص الإشعار",
  sendToAllUsers: "إرسال لجميع المستخدمين",
  notificationSentSuccess: "تم إرسال الإشعار بنجاح.",
  viewNotifications: "عرض الإشعارات",
  noNewNotifications: "لا توجد إشعارات جديدة.",
  markAsRead: "وضع علامة كمقروء",
  markAllAsRead: "وضع علامة على الكل كمقروء",
  newNotification: "إشعار جديد!",
  notifications: "الإشعارات",

  // Transformations Feature
  transformations: "التحولات",
  shareYourProgress: "شارك تقدمك",
  beforePhoto: "الصورة قبل",
  afterPhoto: "الصورة بعد",
  titleOrCaption: "العنوان أو الوصف",
  publishPost: "نشر المنشور",
  likes: "إعجابات",
  comments: "تعليقات",
  addComment: "إضافة تعليق",
  confirmDeletePost: "هل أنت متأكد أنك تريد حذف هذا المنشور؟",
  deletePost: "حذف المنشور",
  confirmDeleteComment: "هل أنت متأكد أنك تريد حذف هذا التعليق؟",
  deleteComment: "حذف التعليق",
  noCommentsYet: "لا توجد تعليقات بعد.",
  addYourComment: "أضف تعليقك...",
  imageTooLarge: "الصورة كبيرة جدًا.",
  invalidImageType: "نوع الملف غير صالح. يرجى رفع صورة.",
  allFieldsAndImagesRequired: "يرجى ملء العنوان ورفع الصورتين.",
  noTransformationsPosted: "لم يتم نشر أي تحولات بعد. كن أول من يشارك!",
  topTransformations: "أبرز التحولات",
  interactions: "تفاعلات",
  postDeletedSuccess: "تم حذف المنشور بنجاح.",
  commentAddedSuccess: "تمت إضافة التعليق بنجاح.",
  commentDeletedSuccess: "تم حذف التعليق بنجاح.",
  manageTransformations: "إدارة التحولات",
  viewPostDetails: "عرض التفاصيل والتعليقات",
};

export const INITIAL_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: DefaultSubscriptionPlanId.BASIC,
    name: "الخطة الأساسية (شهري)",
    price: 10,
    currency: "USD",
    description: "وصول إلى مكتبة التمارين الأساسية.",
    features: [
        {id: 'feat_basic_1', text: "مكتبة التمارين الأساسية"},
        {id: 'feat_basic_2', text: "وصفات مختارة"},
        {id: 'feat_basic_3', text: "تتبع التقدم الأساسي"}
    ],
  },
  {
    id: DefaultSubscriptionPlanId.PREMIUM,
    name: "الخطة المميزة (سنوي)",
    price: 99,
    currency: "USD",
    description: "وصول كامل لجميع التمارين والميزات المتقدمة.",
    features: [
        {id: 'feat_prem_1', text: "جميع التمارين والفيديوهات"},
        {id: 'feat_prem_2', text: "جميع الوصفات"},
        {id: 'feat_prem_3', text: "مساعد التغذية الذكي"},
        {id: 'feat_prem_4', text: "تتبع التقدم المتقدم"},
        {id: 'feat_prem_5', text: "خصم سنوي"}
    ],
  },
  {
    id: DefaultSubscriptionPlanId.ULTIMATE,
    name: "الخطة النهائية (مدى الحياة)",
    price: 299,
    currency: "USD",
    description: "وصول مدى الحياة لجميع المحتويات والميزات المستقبلية.",
    features: [
        {id: 'feat_ult_1', text: "كل شيء في الخطة المميزة"},
        {id: 'feat_ult_2', text: "وصول مدى الحياة"},
        {id: 'feat_ult_3', text: "تحديثات مستقبلية مجانية"}
    ],
  }
];

export const INITIAL_WORKOUT_VIDEOS: WorkoutVideo[] = [
  {
    id: 'vid1',
    title: 'تمارين كارديو صباحية',
    description: 'ابدأ يومك بنشاط مع هذه التمارين القلبية المنعشة.',
    videoUrl: 'https://www.youtube.com/embed/VHyGqsPOUHs?si=Y5z-4h_5yZ0PqY3r', // Example video
    thumbnailUrl: 'https://picsum.photos/seed/vid1/400/225',
    durationMinutes: 15,
    category: 'Cardio',
    uploadedBy: ADMIN_EMAIL, 
    uploadDate: new Date().toISOString(),
  },
  {
    id: 'vid2',
    title: 'تمارين قوة لكامل الجسم',
    description: 'عزز قوتك وبناء عضلاتك مع هذه المجموعة من تمارين القوة.',
    videoUrl: 'https://www.youtube.com/embed/U_q94sA9ys8?si=Z5Q_G9h_k3xR2tP1', // Example video
    thumbnailUrl: 'https://picsum.photos/seed/vid2/400/225',
    durationMinutes: 30,
    category: 'Strength',
    uploadedBy: ADMIN_EMAIL, 
    uploadDate: new Date().toISOString(),
  }
];

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'rec1',
    name: 'سلطة الكينوا المنعشة',
    description: 'سلطة غنية بالبروتين والألياف، مثالية لوجبة خفيفة أو غداء صحي.',
    ingredients: [
      { item: 'كينوا مطبوخة', quantity: '1 كوب' },
      { item: 'خيار مقطع', quantity: '1/2 كوب' },
      { item: 'طماطم شيري مقطعة', quantity: '1/2 كوب' },
      { item: 'بقدونس مفروم', quantity: '1/4 كوب' },
      { item: 'عصير ليمون', quantity: '2 ملعقة كبيرة' },
      { item: 'زيت زيتون', quantity: '1 ملعقة كبيرة' },
    ],
    instructions: [
      'اخلط جميع المكونات في وعاء كبير.',
      'تبل بالملح والفلفل حسب الرغبة.',
      'قدمها باردة أو في درجة حرارة الغرفة.'
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 2,
    imageUrl: 'https://picsum.photos/seed/rec1/400/300',
    category: 'Lunch',
    calories: 350,
    uploadedBy: ADMIN_EMAIL, 
    uploadDate: new Date().toISOString(),
  },
  {
    id: 'rec2',
    name: 'دجاج مشوي بالأعشاب',
    description: 'طبق رئيسي لذيذ وصحي، مثالي للعشاء.',
    ingredients: [
      { item: 'صدور دجاج', quantity: '2 قطعة' },
      { item: 'زيت زيتون', quantity: '1 ملعقة كبيرة' },
      { item: 'روزماري طازج مفروم', quantity: '1 ملعقة صغيرة' },
      { item: 'زعتر طازج مفروم', quantity: '1 ملعقة صغيرة' },
      { item: 'ثوم مهروس', quantity: '1 فص' },
      { item: 'ملح وفلفل', quantity: 'حسب الرغبة' },
    ],
    instructions: [
      'اخلط زيت الزيتون مع الأعشاب والثوم والملح والفلفل.',
      'تبل صدور الدجاج بالخليط واتركها لمدة 15 دقيقة على الأقل.',
      'اشوي الدجاج على الشواية أو في مقلاة حتى ينضج تمامًا.',
      'قدمه مع الخضار المشوية أو السلطة.'
    ],
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    servings: 2,
    imageUrl: 'https://picsum.photos/seed/rec2/400/300',
    category: 'Dinner',
    calories: 400,
    uploadedBy: ADMIN_EMAIL, 
    uploadDate: new Date().toISOString(),
  }
];

export const GEMINI_MODEL_NAME = 'gemini-2.5-flash-preview-04-17';
export const GEMINI_NUTRITION_SYSTEM_INSTRUCTION = "أنت مساعد تغذية خبير. قدم نصائح وإجابات واضحة ومفيدة حول التغذية والوصفات الصحية. تحدث باللغة العربية. اجعل إجاباتك موجزة ومباشرة ما لم يُطلب منك التفصيل.";
export const PDF_MAX_SIZE_BYTES = 5 * 1024 * 1024; // 5MB limit for PDFs in localStorage
